codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_ci_failed: error
    
    patch:
      default:
        target: 85%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*_test.go"
  - "cmd/server/main.go"
  - "docs/**/*"
  - "*.md"
  - "*.yml"
  - "*.yaml"

flags:
  unittests:
    paths:
      - internal/
    carryforward: true

github_checks:
  annotations: true
